import { RecipientGetModel, RecipientPostModel } from "./recipient.model";
new RecipientGetModel();
new RecipientPostModel();
import { CredentialGetModel, CredentialPostModel } from "./credential.model";
new CredentialGetModel();
new CredentialPostModel();
import { IssuanceGetModel, IssuancePostModel } from "./issuance.model";
new IssuanceGetModel();
new IssuancePostModel();
import { GroupModel } from "./group.model";
new GroupModel();
import { EnrollmentModel } from "./enrollment.model";
new EnrollmentModel();
