import { RecipientModel } from "./recipient.model";
new RecipientModel();
import { CredentialModel } from "./credential.model";
new CredentialModel();
import { IssuanceModel } from "./issuance.model";
new IssuanceModel();
import { GroupModel } from "./group.model";
new GroupModel();
import { EnrollmentModel } from "./enrollment.model";
new EnrollmentModel();
